### ISSUE TITLE
ACL to private by default

### ISSUE THREAD

**Issue by krzkrzkrz** [AssetSync/asset_sync#208]
Is it possible to set the ACL for assets uploaded to private by default and let our bucket policy handle the permissions?

**Comment by woqer** [comment]
This still open? here the line https://github.com/AssetSync/asset_sync/blob/e006e5cabb0c705eb385aa4160ae65f1d6bd8d47/lib/asset_sync/storage.rb#L151

**Comment by PikachuEXE** [comment]
By reading the source I think `custom_headers` option can be used?
https://github.com/AssetSync/asset_sync/blob/e006e5cabb0c705eb385aa4160ae65f1d6bd8d47/lib/asset_sync/storage.rb#L171

**Comment by pocari** [comment]
@PikachuEXE 

I added following code to config/initializer/asset_sync.rb

```
    config.custom_headers = {
      '.*' => {
        'x-amz-acl' => 'private'
      }
    }
```

but `Excon::Error::Forbidden: Expected(200) <=> Actual(403 Forbidden)`  has occured.(SignatureDoesNotMatch)

So I checked `fog-aws gems` codes, As @woqer have said, We need to be able to set public option.
@vdh 's #246 PR looks good to me.

**Comment by PikachuEXE** [comment]
The source code looks like this:
https://github.com/AssetSync/asset_sync/blob/e006e5cabb0c705eb385aa4160ae65f1d6bd8d47/lib/asset_sync/storage.rb#L168-L178

So I think it might work if you change `'x-amz-acl' => 'private'` to `public: false`?

Since `file` is initialized as
https://github.com/AssetSync/asset_sync/blob/e006e5cabb0c705eb385aa4160ae65f1d6bd8d47/lib/asset_sync/storage.rb#L148-L153

**Comment by pocari** [comment]
@PikachuEXE At first I thought so.

But If `:public` is true, acl set to `public-read` on `fog-aws gem` side.

https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/storage/file.rb#L152

**Comment by PikachuEXE** [comment]
OK I see what's the issue
Since `public` is a shortcut to set `x-amz-acl` to `public-read` / `private`
And you want that **NOT** to be set
Correct?

**Comment by pocari** [comment]
@PikachuEXE  Since `private` is the default, you do not have to set it, but it is okay for me to explicitly do private.

**Comment by pocari** [comment]
@PikachuEXE  👍

**Comment by PikachuEXE** [comment]
Oh sorry people want those to be handled by bucket policy
So If I make setting `public: nil` as removing `public` option, would that work for you guys?
@pocari @krzkrzkrz @sandstrom @vdh @woqer 

The code change should be like:
```ruby
elsif key = self.config.custom_headers.keys.detect {|k| f.match(Regexp.new(k))} 
   self.config.custom_headers[key].each do |k, value| 
     # Delete value on `nil`
     if value.nil?
       file.delete(k.to_sym)
     else
       file[k.to_sym] = value
     end
   end
   log "Overwriting matching file #{f} with custom headers #{headers.to_s}" 
 end

**Comment by pocari** [comment]
@PikachuEXE  
I think that it is better to control with the new property than the property called custom_header.

Because I think that the setting will be as follows,

```

    config.custom_headers = {
      '.*' => {
        "public" => nil
      }
    }
```

but, In fact there is no http header called `public`.

**Comment by pocari** [comment]
```
# configuration
# default value is true for compatibility.
config.config.fog_public = true | false, nil | :default

# in update_file method
...

case
when config.fog_public == :default
  file.delete(:public)
when config.fog_public
  file[:public] = true
else
  file[:public] = false
els
```

**Comment by PikachuEXE** [comment]
I think the default should still be `true`, but with `nil`
or some special value to indicate deletion of `:public` key from `file`

**Comment by pocari** [comment]
@PikachuEXE  umm... 

> some special value to indicate deletion of :public

how about this?

```
# configuration
# default value is true for compatibility.
config.default_acl = true

# in update_file method
...

if config.default_acl
  file.delete(:public)
end
```

**Comment by PikachuEXE** [comment]
I think I will just add `fog_public` with special values
`default_acl` is not very understandable for people who don't know what ACL means (Is it AWS specific?)

**Comment by pocari** [comment]
@PikachuEXE 

> default_acl is not very understandable for people who don't know what ACL means (Is it AWS specific?)
Good point

> I think I will just add fog_public with special values
👍

**Comment by woqer** [comment]
I'd just try to respect the configs from provider instead of (re)setting them at the gem level. Is it possible to just get rid of the `public` option? If people need a different setup (public vs private) they should configure it somewhere else, or explicitly override it, but not set it by default.

PD: the concept of Access Control List (ACL) have been around in computing for some decades https://en.wikipedia.org/wiki/Access_control_list

**Comment by PikachuEXE** [comment]
@woqer 
**If** this was written by me I will make it disabled by default so that you need to opt-in instead of opt-out
But for now since I don't want to bump major version *yet*
Let's add the option and see if that fits people's need first
If it does we can change the default value on next major version bump

**Comment by PikachuEXE** [comment]
I am releasing a new version with #377 if no one objects~

**Comment by sandstrom** [comment]
@PikachuEXE Awesome! 🎉

**Comment by aberenshtein** [comment]
@pocari not sure if this is still relevant, but this works for me
`    config.custom_headers = {
      '.*' => {
        'acl' => 'bucket-owner-full-control'
      }
    }
 `
https://www.rubydoc.info/gems/fog-aws/1.2.1/Fog/Storage/AWS/File#acl-instance_method
