### ISSUE TITLE
Slug Size Limit Workaround

### ISSUE THREAD

**Issue by Undistraction** [AssetSync/asset_sync#219]
My application has finally crossed Heroku's Slug size limit threshold meaning I can no-longer deploy. 

It seems that even though Asset Sync compiles all my assets and uploads them to S3, they are still included in the Slug size. 

Is there any way to have Heroku dump the assets once Asset Sync has dealt with them so that they aren't included in the slug size?

Or should I be looking at precompiling locally, then excluding the assets from being pushed up to Heroku using a .slugignore?

**Comment by Systho** [comment]
I know this is a long closed thread but I had the same problem and did not want to precompile locally. So I used the following buildpack which allowed me to remove files just before the slug is created (the .slugignore solution would not have worked since I needed the files to be present during the build) : https://github.com/moravcik/heroku-buildpack-post-build-clean
