### ISSUE TITLE
Make provider gems optional

### ISSUE THREAD

**Issue by hughevans** [AssetSync/asset_sync#292]
Hi,

Great gem, love it. But if you’ve now gone to the trouble to split out the provider support into separate gems, why make them all dependencies of `fog`? I just want AWS support (so I can use the `asset_sync` gem), but now I have this in my `Gemfile.lock`:

```
    fog (1.27.0)
      fog-atmos
      fog-aws (~> 0.0)
      fog-brightbox (~> 0.4)
      fog-core (~> 1.27, >= 1.27.3)
      fog-ecloud
      fog-json
      fog-profitbricks
      fog-radosgw (>= 0.0.2)
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
      nokogiri (~> 1.5, >= 1.5.11)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.0.8)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.7.1)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-core (1.28.0)
      builder
      excon (~> 0.38)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-ecloud (0.0.2)
      fog-core
      fog-xml
    fog-json (1.0.0)
      multi_json (~> 1.0)
    fog-profitbricks (0.0.1)
      fog-core
      fog-xml
      nokogiri
    fog-radosgw (0.0.3)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-sakuracloud (1.0.0)
      fog-core
      fog-json
    fog-serverlove (0.1.1)
      fog-core
      fog-json
    fog-softlayer (0.4.0)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.0)
      fog-core
      fog-json
    fog-terremark (0.0.3)
      fog-core
      fog-xml
    fog-vmfusion (0.0.1)
      fission
      fog-core
    fog-voxel (0.0.2)
      fog-core
      fog-xml
    fog-xml (0.1.1)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
```

I’m happy to do this:

```
gem 'fog'
gem 'fog-aws'
```

Thanks.

**Comment by eljojo** [comment]
Please! I'd love to see this happening too!

``fog`` could be changed to ``fog-aws`` in https://github.com/rumblelabs/asset_sync/blob/051c3849c89abea2ec908213717bde800e83e223/asset_sync.gemspec#L21
I guess  the version would have to be ``0.1.0``

Also, it's not necessary to explicitly define ``fog`` **and** ``fog-aws``, because ``fog`` is a dependency of ``fog-aws``

**Comment by plribeiro3000** [comment]
@hughevans Thats a good question to be made at [`fog`](https://github.com/fog/fog) i believe.
We know the pain of so much gems as dependencies but we need them as dependency for now because we did not release a major version (where we can break things and remove a lot of features) yet. There is still a lot of providers to be extracted before we can get to this step. Until there i'm not sure how we will handle the situation.

About the dependency on `fog-aws` only you have my :+1: if this is intended to work on `AWS` only.

**Comment by itsmrwave** [comment]
I share @hughevans's sentiments ... the user should be able to require the fog gem that they need. Maybe give a table showing the provider and the fog dependency the developer to choose for themselves what to add in the Gemfile.

**Comment by plribeiro3000** [comment]
@itsmrwave Please, share this thought at `fog`.

This is the wrong place to ask/share `fog` ideas/concerns.

**Comment by itsmrwave** [comment]
@plribeiro3000 :+1: 

@hughevans If you still have this problem you can try out the [s3_asset_sync ](https://rubygems.org/gems/s3_asset_sync/versions/0.1.1) gem.

**Comment by willglynn** [comment]
`fog` is being refactored and still depends on all the provider gems, but you might try:

    gem 'fog', '~> 1.30', require: false
    gem 'fog-aws'
    gem 'asset_sync'

This doesn't help the size of your `Gemfile.lock`, but it does save a few cycles:

    $ irb -rbundler/setup -rbenchmark
    2.2.0 :001 > puts Benchmark.measure { require 'fog' }
      0.600000   0.230000   0.830000 (  0.825120)
    2.2.0 :002 > ObjectSpace.count_objects[:TOTAL]
     => 309369 
    $ irb -rbundler/setup -rbenchmark
    2.2.0 :001 > puts Benchmark.measure { require 'fog/aws' }
      0.310000   0.120000   0.430000 (  0.424121)
    2.2.0 :002 > ObjectSpace.count_objects[:TOTAL]
     => 212360

**Comment by plribeiro3000** [comment]
@willglynn :+1:

**Comment by jeremyhaile** [comment]
@plribeiro3000 This has been addressed in `fog`. You can now depend on `fog-core` and the providers are being broken out into separate gems that can be included in projects that require them.

**Comment by plribeiro3000** [comment]
@jeremyhaile Actually if you depend on `fog-core`you are not getting any provider at all and by requiring an extracted provider you get `fog-core` together so the right path is not be corrected in `fog`but here depending only on `fog-aws` if this code works only on AWS.

**Comment by jeremyhaile** [comment]
@plribeiro3000 Yes, I want to do something like the following:
```ruby
require 'fog-aws'
require 'asset_sync'
```

And not have all of `fog` pulled into my project. However, since `asset_sync` lists a dependency on `fog` instead of `fog-core`, it forces my project to pull in all of fog's providers.

**Comment by plribeiro3000** [comment]
Yeah. The only thing is that `asset_sync` should depend on `fog-aws` and not `fog-core`.
And by `asset_sync` depending on `fog-aws` you wont need to require `fog-aws` at all because you will get it for free.

**Comment by willglynn** [comment]
Why should `asset_sync` depend on `fog-aws` instead of `fog-core`? I mean, I used it with AWS, but it works with any of the Fog providers, right?

**Comment by plribeiro3000** [comment]
That was my original question @willglynn 

But the documentation says `S3` onlye. See [here](https://github.com/AssetSync/asset_sync#asset-sync).

**Comment by willglynn** [comment]
Scroll down to the [Fog section](https://github.com/AssetSync/asset_sync#fog-required):

> **fog_provider**: your storage provider AWS (S3) or Rackspace (Cloud Files) or Google (Google Storage)

…with examples for each.

**Comment by plribeiro3000** [comment]
Actually the README does list other providers so there is nothing to change here.
`AssetSync` should depend on ´fog´ and `fog` will depend on all providers. As the time pass more providers will be extracted and this list will just keep growing so it the amount of dependencies is a pain (which should not be, we dealt with the loading time already) `AssetSync` should find another solution.

But as i can see this project is kind of dead. No feedback from the maintainers nor any commit since `12 Dec 2014`.

**Comment by plribeiro3000** [comment]
I believe that `AssetSync` should not depend on `fog` at all and the user should require the `provider` he wants manually. Then this wont be a problem anymore.

**Comment by PikachuEXE** [comment]
`2.0.0` released
Have a try!
