### ISSUE TITLE
Minimum S3 policy possibly incorrect

### ISSUE THREAD

**Issue by jkburges** [AssetSync/asset_sync#355]
I found that the policy referred to [in the README](https://github.com/AssetSync/asset_sync#amazon-aws-iam-users) is not correct.  Below is what was needed (for me, at least):

```json
{
  "Action": "s3:ListBucket",
  "Effect": "Allow",
  "Resource": "arn:aws:s3:::<bucket name>"
},
{
  "Action": "s3:PutObject*",
  "Effect": "Allow",
  "Resource": "arn:aws:s3:::<bucket name>/*"
}
``` 

Notably, it seems as though the library needs to list bucket contents (rather than all buckets) - presumably to determine whether or not there is any syncing to do.

I'm happy to put up a PR with a documentation change, so long as someone else can confirm that the above is correct for them.

**Comment by PikachuEXE** [comment]
Let's just put a PR for the doc
If someone else use the updated one and failed, we can change it back without much damage :)

**Comment by Chris-Boyle** [comment]
I am attempting to use a user for uploading with assets_sync and still getting the 403 forbidden error.
Here is my policy for that user
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::bucket-name",
            "Effect": "Allow"
        },
        {
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::bucket-name/*",
            "Effect": "Allow"
        }
    ]
}`
I was able to confirm using the AWS CLI that I am able to upload assets though
`aws s3api put-object --bucket bucket-name --key shire-test --body test --profile appuser`
Any tips?

**Comment by PikachuEXE** [comment]
If you set `existing_remote_files` to anything other than `keep`
Then you might need to allow "destroy" in bucket (called at https://github.com/AssetSync/asset_sync/blob/master/lib/asset_sync/storage.rb#L124)
Otherwise `ListBucket` & `PutObject` should be enough for `bucket.files.each` & `buckets.files.create` in https://github.com/AssetSync/asset_sync/blob/master/lib/asset_sync/storage.rb

**Comment by Chris-Boyle** [comment]
@PikachuEXE would there be any difference in using a Federated AWS account?  I have a personal account and can get things to work but my Work one is Federated and failing.  I also have forward slashes in my secret.  Is that okay?

**Comment by Chris-Boyle** [comment]
@PikachuEXE 
`Caused by:
Excon::Error::Forbidden: Expected(200) <=> Actual(403 Forbidden)
excon.error.response
  :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5CE9848CCDD33F06</RequestId><HostId>xxxxxxxxxx+fbirawHknDd/f/bvMFedZ8=</HostId></Error>"
  :cookies       => [
  ]
  :headers       => {
    "Connection"       => "close"
    "Content-Type"     => "application/xml"
    "Date"             => "Wed, 01 Aug 2018 19:59:19 GMT"
    "Server"           => "AmazonS3"
    "x-amz-id-2"       => "xxxxxxxxxx+xxxxxxxxxx/f/xxxxxxxxxx="
    "x-amz-request-id" => "5CE9848CCDD33F06"
  }
  :host          => "s3-dev.s3.amazonaws.com"
  :local_address => "xxxxxxxxxx"
  :local_port    => 56924
  :path          => "/assets/3c5aab194614e29f6e6b3b16ebcfe34d.svg"
  :port          => 443
  :reason_phrase => "Forbidden"
  :remote_ip     => "xxxxxxxxxx"
  :status        => 403
  :status_line   => "HTTP/1.1 403 Forbidden\r\n"
/Users/cb/.rvm/gems/ruby-2.4.3/gems/excon-0.62.0/lib/excon/middlewares/expects.rb:7:in `response_call'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/excon-0.62.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/excon-0.62.0/lib/excon/connection.rb:414:in `response'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/excon-0.62.0/lib/excon/connection.rb:263:in `request'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
/Users/cb /.rvm/gems/ruby-2.4.3/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:9:in `request'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/fog-aws-3.0.0/lib/fog/aws/storage.rb:613:in `_request'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/fog-aws-3.0.0/lib/fog/aws/storage.rb:608:in `request'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/fog-aws-3.0.0/lib/fog/aws/requests/storage/put_object.rb:46:in `put_object'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/fog-aws-3.0.0/lib/fog/aws/models/storage/file.rb:220:in `save'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/asset_sync-2.0.0/lib/asset_sync/storage.rb:196:in `upload_file'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/asset_sync-2.0.0/lib/asset_sync/storage.rb:209:in `block in upload_files'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/asset_sync-2.0.0/lib/asset_sync/storage.rb:207:in `each'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/asset_sync-2.0.0/lib/asset_sync/storage.rb:207:in `upload_files'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/asset_sync-2.0.0/lib/asset_sync/storage.rb:223:in `sync'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/asset_sync-2.0.0/lib/asset_sync/asset_sync.rb:29:in `block in sync'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/asset_sync-2.0.0/lib/asset_sync/asset_sync.rb:51:in `with_config'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/asset_sync-2.0.0/lib/asset_sync/asset_sync.rb:28:in `sync'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/asset_sync-2.0.0/lib/tasks/asset_sync.rake:5:in `block (2 levels) in <top (required)>'
/Users/cb/.rvm/gems/ruby-2.4.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/cb/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
/Users/cb/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:sync
(See full trace by running task with --trace)`

**Comment by Chris-Boyle** [comment]
Here is the Users policy
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::s3-dev",
            "Effect": "Allow"
        },
        {
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::s3-dev/*",
            "Effect": "Allow"
        },
        {
            "Action": "s3:ListAllMyBuckets",
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}`

**Comment by Chris-Boyle** [comment]
@PikachuEXE 
I ended up getting it to work with adding 
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::s3-bucket"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::s3-bucket/*"
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor3",
            "Effect": "Allow",
            "Action": "s3:PutObjectAcl",
            "Resource": "arn:aws:s3:::s3-bucket/*"
        }
    ]
}

**Comment by jkburges** [comment]
Maybe https://github.com/AssetSync/asset_sync/pull/356 needs to be reverted then, if `ListAllMyBuckets` *is* needed (sometimes - why?)?

**Comment by PikachuEXE** [comment]
@jkburges If you look at the stacktrace provided by @Chris-Boyle 
The operation is "put object"
Which means maybe the policy allowing "put object" might be incorrect before (I dunno how)

**Comment by jkburges** [comment]
@Chris-Boyle's policy doesn't have the `*` on the end, i.e. "arn:aws:s3:::s3-bucket/" as opposed to "arn:aws:s3:::<bucket name>/*". Maybe that is it?

**Comment by Chris-Boyle** [comment]
@jkburges the putObject does have a * it just hides it in the comment for some reason.  I just did a little more testing and I don't think the ListAllMyBuckets is needed but the PutObjectAcl is needed or the initial upload and any new assets being uploaded will fail.
![image](https://user-images.githubusercontent.com/20329437/43558934-60b528de-95d1-11e8-953e-2841ce746f50.png)

**Comment by jkburges** [comment]
> PutObjectAcl is needed or the initial upload and any new assets being uploaded will fail

Yeah, I reckon this is the key. Probably when I was testing, I was syncing something that was already there. Nice one.

**Comment by Chris-Boyle** [comment]
@jkburges  Aha!! I see the doc says to use PutObject* and I have PutObject.  I just tested with the wildcard at the end without the PutObjectAcl and it worked.
